# Generated by Django 5.2.5 on 2025-09-27 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeration', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Перше блюдо', 'Перше блюдо'), ('Друге блюдо', 'Друге блюдо'), ('Десерт', 'Десерт'), ('Напій', 'Напій'), ('Закуска', 'Закуска'), ('Салат', 'Салат'), ('Гостра', 'Гостра')], max_length=100)),
                ('price', models.PositiveIntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], default='1', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('date_n_time', models.DateTimeField()),
                ('time_of_reservation', models.DateTimeField(auto_now_add=True)),
                ('number_of_people', models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1')),
                ('reservator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stravu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunger.position')),
            ],
        ),
    ]
