# Generated by Django 5.2.5 on 2025-10-04 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeration', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Перше блюдо', 'Перше блюдо'), ('Друге блюдо', 'Друге блюдо'), ('Десерт', 'Десерт'), ('Напій', 'Напій'), ('Закуска', 'Закуска'), ('Салат', 'Салат'), ('Гостра', 'Гостра')], max_length=100)),
                ('price', models.PositiveIntegerField(default=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='stravu',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservator',
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunger.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
