# Generated by Django 5.2.5 on 2025-10-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0002_dish_remove_reservation_stravu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='numeration',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='shopcart',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique_item_user'),
        ),
        migrations.AddField(
            model_name='laststep',
            name='carts',
            field=models.ManyToManyField(to='hunger.shopcart'),
        ),
        migrations.AddField(
            model_name='laststep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
