# Generated by Django 5.2.5 on 2025-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0003_laststep_alter_dish_name_alter_dish_numeration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laststep',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
