# Generated by Django 5.2.5 on 2025-11-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0006_alter_dish_image_alter_shopcart_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carter',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunger.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hunger.order')),
            ],
        ),
    ]
